name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          artifact-name: pseudo
          version-tag: v1.2.3
          image-digest: sha256:abc123
          release-workflow-ref: tmknom/release-workflows/.github/workflows/go.yml@abc123

      - name: Verify
        env:
          RELEASE_NOTE: ${{ steps.exercise.outputs.release-note-path }}
        run: |
          set -x
          grep "https://github.com/${GITHUB_REPOSITORY}/releases/download/1.2.3/pseudo_1.2.3_linux_amd64" "${RELEASE_NOTE}"
          grep "docker pull ghcr.io/${GITHUB_REPOSITORY}@sha256:abc123" "${RELEASE_NOTE}"
          grep "https://github.com/tmknom/release-workflows/.github/workflows/go.yml@abc123" "${RELEASE_NOTE}"
